In [1]:
%load_ext autoreload
%autoreload 2

In [75]:
import pyneb as pn
from helper_functions import *

In [3]:
DataFileDict = {'H1': {'rec': 'h_i_rec_SH95.fits'},
                'O2': {'atom': 'o_ii_atom_FFT04.dat', 'coll': 'o_ii_coll_Kal09.dat'},
                'S2': {'coll': 's_ii_coll_TZ10.dat'}}

pn.atomicData.setDataFileDict(DataFileDict)

In [62]:
diag = pn.Diagnostics()
diag.addDiag('[SII] 6716/6731', ('S2', 'L(6716)/L(6731)', 'RMS([E(6716), E(6731)])'))

In [61]:
H1 = pn.RecAtom('H', 1) #use on the no brackets
O2 = pn.Atom('O', 2)    #use with brackets
O3 = pn.Atom('O', 3)
S2 = pn.Atom('S', 2) 

# Define the number of Monte Carlo iterations:
n = 10 #1500, using 10 as a test case once I get the code working I can increase this

H1: Atomic data: Storey and Hummer 1995, MNRAS, 272, 41


In [6]:
# S2.getCritDensity()       #temperature needed
# S2.getLowDensRatio()      #
# S2.getHighDensRatio()     #

In [7]:
#generating random ratios for OIII and SII for testing purposes
np.random.seed(100101)
n = 10 
random_OIII_ratios = np.random.exponential(scale = 0.1, size = n)
random_SII_ratios = np.random.uniform(low = 0.8, high = 1.2, size = n)

In [26]:
#"[OIII] 4363/5007+" : ('O3', 'L(4363)/(L(5007)+L(4959))', 'RMS([E(5007)*L(5007)/(L(5007)+L(4959)), E(4959)*L(4959)/(L(5007)+L(4959)), E(4363)])')
temp, den = diag.getCrossTemDen('[OIII] 4363/5007+', '[SII] 6716/6731', random_OIII_ratios, random_SII_ratios)

In [27]:
display_summary(random_OIII_ratios, random_SII_ratios, temp, den)

OIII 4363/5007+ = 0.004, SII 6716/6731 = 1.038, T = 9191 K, n_e = 591 cm-3
OIII 4363/5007+ = 0.241, SII 6716/6731 = 0.832, T = nan K, n_e = nan cm-3
OIII 4363/5007+ = 0.002, SII 6716/6731 = 1.050, T = 8125 K, n_e = 537 cm-3
OIII 4363/5007+ = 0.074, SII 6716/6731 = 0.954, T = nan K, n_e = nan cm-3
OIII 4363/5007+ = 0.220, SII 6716/6731 = 0.854, T = nan K, n_e = nan cm-3
OIII 4363/5007+ = 0.116, SII 6716/6731 = 0.832, T = nan K, n_e = nan cm-3
OIII 4363/5007+ = 0.010, SII 6716/6731 = 0.826, T = 12691 K, n_e = 1563 cm-3
OIII 4363/5007+ = 0.014, SII 6716/6731 = 0.863, T = 14755 K, n_e = 1420 cm-3
OIII 4363/5007+ = 0.004, SII 6716/6731 = 0.935, T = 9616 K, n_e = 907 cm-3
OIII 4363/5007+ = 0.075, SII 6716/6731 = 1.094, T = nan K, n_e = nan cm-3


In [36]:
test_temp = replace_NaNs(temp, 15000)

In [37]:
test_temp

array([ 9190.79711589, 15000.        ,  8125.39723659, 15000.        ,
       15000.        , 15000.        , 12691.28739333, 14755.19713442,
        9615.67753289, 15000.        ])

In [43]:
test_den = replace_NaNs(den, 100)

In [44]:
test_den

array([ 590.76307458,  100.        ,  537.13473049,  100.        ,
        100.        ,  100.        , 1562.78375759, 1419.84443724,
        906.56474788,  100.        ])

In [45]:
display_summary(random_OIII_ratios, random_SII_ratios, test_den, test_den)

OIII 4363/5007+ = 0.004, SII 6716/6731 = 1.038, T = 591 K, n_e = 591 cm-3
OIII 4363/5007+ = 0.241, SII 6716/6731 = 0.832, T = 100 K, n_e = 100 cm-3
OIII 4363/5007+ = 0.002, SII 6716/6731 = 1.050, T = 537 K, n_e = 537 cm-3
OIII 4363/5007+ = 0.074, SII 6716/6731 = 0.954, T = 100 K, n_e = 100 cm-3
OIII 4363/5007+ = 0.220, SII 6716/6731 = 0.854, T = 100 K, n_e = 100 cm-3
OIII 4363/5007+ = 0.116, SII 6716/6731 = 0.832, T = 100 K, n_e = 100 cm-3
OIII 4363/5007+ = 0.010, SII 6716/6731 = 0.826, T = 1563 K, n_e = 1563 cm-3
OIII 4363/5007+ = 0.014, SII 6716/6731 = 0.863, T = 1420 K, n_e = 1420 cm-3
OIII 4363/5007+ = 0.004, SII 6716/6731 = 0.935, T = 907 K, n_e = 907 cm-3
OIII 4363/5007+ = 0.075, SII 6716/6731 = 1.094, T = 100 K, n_e = 100 cm-3


In [46]:
dist_getcritdensity(O3, temp, return_type='df')

N_crit_1    N_crit_2     N_crit_3       N_crit_4      N_crit_5  \
0       0.0  486.841599  3445.096458  673104.068053  2.353649e+07   
1       NaN         NaN          NaN            NaN           NaN   
2       0.0  466.448887  3314.979913  647163.211778  2.257348e+07   
3       NaN         NaN          NaN            NaN           NaN   
4       NaN         NaN          NaN            NaN           NaN   
5       NaN         NaN          NaN            NaN           NaN   
6       0.0  540.856653  3745.716658  743756.513030  2.667062e+07   
7       0.0  566.680422  3866.368804  779348.651541  2.856261e+07   
8       0.0  494.362079  3491.056341  682768.717175  2.390225e+07   
9       NaN         NaN          NaN            NaN           NaN   

    Temperature  
0   9190.797116  
1           NaN  
2   8125.397237  
3           NaN  
4           NaN  
5           NaN  
6  12691.287393  
7  14755.197134  
8   9615.677533  
9           NaN

In [47]:
dist_getcritdensity(O3, test_temp, return_type='df')

N_crit_1    N_crit_2     N_crit_3       N_crit_4      N_crit_5  \
0       0.0  486.841599  3445.096458  673104.068053  2.353649e+07   
1       0.0  569.490652  3878.715258  783294.414469  2.877727e+07   
2       0.0  466.448887  3314.979913  647163.211778  2.257348e+07   
3       0.0  569.490652  3878.715258  783294.414469  2.877727e+07   
4       0.0  569.490652  3878.715258  783294.414469  2.877727e+07   
5       0.0  569.490652  3878.715258  783294.414469  2.877727e+07   
6       0.0  540.856653  3745.716658  743756.513030  2.667062e+07   
7       0.0  566.680422  3866.368804  779348.651541  2.856261e+07   
8       0.0  494.362079  3491.056341  682768.717175  2.390225e+07   
9       0.0  569.490652  3878.715258  783294.414469  2.877727e+07   

    Temperature  
0   9190.797116  
1  15000.000000  
2   8125.397237  
3  15000.000000  
4  15000.000000  
5  15000.000000  
6  12691.287393  
7  14755.197134  
8   9615.677533  
9  15000.000000

In [54]:
np.random.seed(100101)
random_OIII5007_intensities = np.random.uniform(low = 1, high = 100, size = n)
random_OIII4969_intensities = random_OIII5007_intensities/3
random_OIII4363_intensities = np.random.uniform(low = 1, high = 10, size = n)


test_hbeta = 50

random_OIII5007_int = convert_int_relative_to_hbeta(random_OIII5007_intensities, test_hbeta)
random_OIII4969_int = convert_int_relative_to_hbeta(random_OIII4969_intensities, test_hbeta)
random_OIII4363_int = convert_int_relative_to_hbeta(random_OIII4363_intensities, test_hbeta)

In [55]:
OIII_5007_ion_abundance = ionic_abundance(O3, random_OIII5007_int, test_temp, test_den, 5007)
OIII_4969_ion_abundance = ionic_abundance(O3, random_OIII4969_int, test_temp, test_den, 4969)
OIII_4363_ion_abundance = ionic_abundance(O3, random_OIII4363_int, test_temp, test_den, 4363)



In [71]:
total_OIII_abundance = np.sum([OIII_5007_ion_abundance, OIII_4969_ion_abundance, OIII_4363_ion_abundance], axis = 0)

In [73]:
12 + np.log10(total_OIII_abundance)

array([9.09172969, 7.76052021, 9.52006374, 7.85288276, 7.79263228,
       7.68363181, 7.66692533, 7.53460713, 8.75519127, 8.02446035])

In [69]:
S2.getLowDensRatio(to_eval = 'L(6716)/L(6731)', tem=1.5e4)
#getting NaN but it could be due to my SII data PyNeb is using

nan

In [70]:
S2.getHighDensRatio(to_eval = 'L(6716)/L(6731)', tem=1.5e4)

nan

In [79]:
tem, den = compute_cross_temden((random_OIII_ratios, random_SII_ratios))

In [ ]:
#generating random ratios for OIII and SII for testing purposes
np.random.seed(100101)
n = 10000 
random_OIII_ratios = np.random.exponential(scale = 0.1, size = n)
random_SII_ratios = np.random.uniform(low = 0.8, high = 1.2, size = n)

cross_temden(random_OIII_ratios, random_SII_ratios, multiprocess = True)